apiVersion: v1
kind: Service
metadata:
    name: "akslearningcdonado-7d59"
    labels:
        app: "akslearningcdonado-7d59"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "akslearningcdonado-7d59"